# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-18 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_grouptask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(max_length=100)),
                ('host_group', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
            ],
        ),
    ]
