# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Age',
            field=models.IntegerField(default=19),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='CreateDate',
            field=models.DateField(default='2017-04-07'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='memo',
            field=models.TextField(default='xxxxxx'),
        ),
    ]
