# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_group_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Args',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('no_nmae', models.CharField(max_length=50)),
            ],
        ),
    ]
