# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-05 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('file_path', models.CharField(max_length=256)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u540d',
                'verbose_name_plural': '\u6587\u4ef6\u8def\u5f84',
            },
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=30)),
                ('server_id', models.CharField(max_length=30)),
                ('serveropen_date', models.CharField(max_length=30)),
                ('serveropen_time', models.CharField(max_length=30)),
                ('is_recall', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_name', models.CharField(max_length=30)),
                ('code_name', models.CharField(max_length=30)),
                ('basegroup_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='gameplat_gameid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameplat_game_name', models.CharField(max_length=100)),
                ('gameplat_game_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=30)),
                ('codename', models.CharField(max_length=30)),
                ('iconimage', models.ImageField(upload_to=b'img')),
            ],
        ),
        migrations.CreateModel(
            name='gameproject_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameproject_name', models.CharField(max_length=30)),
                ('gameproject_name_chinese', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='plat_name_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameplat_game_name', models.CharField(max_length=100)),
                ('gameplat_game_name_chinese', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('log', models.TextField(max_length=30)),
                ('last_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u540d',
                'verbose_name_plural': '\u5bc6\u7801',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='zabbix_create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='zabbix_delete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('last_ti', models.DateField()),
                ('user', models.CharField(max_length=20)),
                ('status_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='typeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserType'),
        ),
        migrations.AddField(
            model_name='gameproject',
            name='user',
            field=models.ManyToManyField(to='web.User'),
        ),
        migrations.AddField(
            model_name='gameplat',
            name='gameproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.GameProject'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.GamePlat'),
        ),
    ]
