# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=20)),
                ('basegroup_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
