# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaifu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='YunYingInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=20)),
                ('server_id', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('is_recall', models.TextField(default='0')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaifu.Adapter')),
            ],
        ),
    ]
