# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7c7b\u578b',
                'verbose_name_plural': '\u7528\u6237\u7c7b\u578b',
            },
        ),
    ]
