# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app06', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(max_length=256)),
                ('IP', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': '\u7528\u6237\u540d\u79f0',
                'verbose_name_plural': 'IP\u5217\u8868',
            },
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
